version: "3.9"

services:
  iuttessa:
    build: .
    container_name: iuttessa
    ports:
      - "8002:8000"
    volumes:
      - .:/app:cached
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=iuttessa.settings

volumes:
  static_volume:
    driver: local
    driver_opts:
      type: none
      device: ./staticfiles
      o: bind
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: ./media
      o: bind
