version: "3.9"

services:
  iuttessa:
    build: .
    container_name: iuttessa
    ports:
      - "8002:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    restart: always

volumes:
  static_volume:
