version: "3.9"

services:
  iuttessa:
    build: .
    container_name: iuttessa
    ports:
      - "8002:8000"
    volumes:
      - .:/app:cached
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=iuttessa.settings
      - DOCKER_CONTAINER=true  # 🔥 Marqueur Docker (même si on ne l'utilise pas ici)

volumes:
  static_volume:
  media_volume: