# Generated by Django 5.2.5 on 2025-08-14 11:55

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Contenu')),
                ('block_type', models.CharField(choices=[('hero', 'Section Hero'), ('about', 'À Propos'), ('contact', 'Contact'), ('news', 'Communiqués/Actualités'), ('gallery', 'Galerie Photos'), ('testimonials', 'Témoignages'), ('services', 'Services'), ('stats', 'Statistiques'), ('team', 'Notre Équipe'), ('custom', 'Contenu Personnalisé')], default='custom', max_length=50, verbose_name='Type de bloc')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], default='active', max_length=10, verbose_name='Statut')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='Image')),
                ('link_url', models.URLField(blank=True, verbose_name='Lien (optionnel)')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Texte du lien')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloc de page',
                'verbose_name_plural': 'Blocs de page',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
