# Generated by Django 5.2.5 on 2025-08-14 12:59

import django.core.validators
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='document',
            field=models.FileField(blank=True, help_text='PDF, Word, Excel, PowerPoint, etc.', null=True, upload_to=pages.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'rtf']), pages.models.validate_file_size], verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='document_title',
            field=models.CharField(blank=True, help_text='Nom affiché pour le téléchargement', max_length=200, verbose_name='Titre du document'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='video_embed_code',
            field=models.TextField(blank=True, help_text='Code iframe ou embed pour vidéos externes', verbose_name="Code d'intégration"),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='video_file',
            field=models.FileField(blank=True, help_text='Pour vidéos locales (MP4, WebM) - Max 50MB', null=True, upload_to=pages.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'avi', 'mov']), pages.models.validate_file_size], verbose_name='Fichier vidéo'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Image de prévisualisation', null=True, upload_to='videos/thumbnails/', verbose_name='Miniature vidéo'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='video_type',
            field=models.CharField(choices=[('local', 'Vidéo locale (upload)'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('embed', "Code d'intégration")], default='local', max_length=20, verbose_name='Type de vidéo'),
        ),
        migrations.AddField(
            model_name='pageblock',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL YouTube, Vimeo ou autre', verbose_name='URL de la vidéo'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Section Hero'), ('about', 'À Propos'), ('contact', 'Contact'), ('news', 'Communiqués/Actualités'), ('gallery', 'Galerie Photos'), ('documents', 'Documents/Fichiers'), ('videos', 'Vidéos'), ('testimonials', 'Témoignages'), ('services', 'Services'), ('stats', 'Statistiques'), ('team', 'Notre Équipe'), ('custom', 'Contenu Personnalisé')], default='custom', max_length=50, verbose_name='Type de bloc'),
        ),
        migrations.AlterField(
            model_name='pageblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Image principale du bloc', null=True, upload_to='blocks/images/', verbose_name='Image'),
        ),
    ]
