# Generated by Django 5.2.5 on 2025-10-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0002_pageblock'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code du cours'),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Crédits'),
        ),
        migrations.AddField(
            model_name='course',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academique.filiere', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Cours obligatoire'),
        ),
    ]
