# Generated by Django 5.2.5 on 2025-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_media_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Section Hero'), ('about', 'À Propos'), ('contact', 'Contact'), ('news', 'Communiqués/Actualités'), ('gallery', 'Galerie Photos'), ('documents', 'Documents/Fichiers'), ('videos', 'Vidéos'), ('testimonials', 'Témoignages'), ('services', 'Services'), ('stats', 'Statistiques'), ('team', 'Notre Équipe'), ('custom', 'Contenu Personnalisé'), ('academic_filieres', 'Filières (Public)'), ('academic_admission', 'Admission & Inscription'), ('academic_frais', 'Frais de Scolarité'), ('academic_documents', 'Documents Requis')], default='custom', max_length=50, verbose_name='Type de bloc'),
        ),
    ]
