# Generated by Django 5.2.5 on 2025-08-18 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_inscription', models.BooleanField(default=True, verbose_name='Email pour inscription')),
                ('email_documents', models.BooleanField(default=True, verbose_name='Email pour documents')),
                ('email_validation', models.BooleanField(default=True, verbose_name='Email pour validation')),
                ('email_rappels', models.BooleanField(default=True, verbose_name='Email pour rappels')),
                ('email_info', models.BooleanField(default=False, verbose_name='Email pour informations')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Notifications push activées')),
                ('frequence_email', models.CharField(choices=[('immediate', 'Immédiate'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire')], default='immediate', max_length=10, verbose_name='Fréquence des emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_envoye',
            field=models.BooleanField(default=False, verbose_name='Email envoyé'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expediteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default=1, max_length=200, verbose_name='Titre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='url_action',
            field=models.CharField(blank=True, max_length=200, verbose_name="URL d'action"),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('inscription_complete', 'Inscription complétée'), ('inscription_validee', 'Inscription validée'), ('inscription_rejetee', 'Inscription rejetée'), ('document_upload', 'Document téléchargé'), ('document_valide', 'Document validé'), ('document_rejete', 'Document rejeté'), ('document_manquant', 'Document manquant'), ('profil_complete', 'Profil complété'), ('profil_incomplet', 'Profil incomplet'), ('validation_profil', 'Validation du profil'), ('import_success', 'Import réussi'), ('import_error', "Erreur d'import"), ('rappel', 'Rappel'), ('info', 'Information'), ('alerte', 'Alerte'), ('autre', 'Autre')], default='info', max_length=50, verbose_name='Type de notification'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['destinataire', 'lu'], name='notificatio_destina_353850_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type_notification'], name='notificatio_type_no_ba8ea8_idx'),
        ),
        migrations.AddField(
            model_name='preferencenotification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
