name: CI/CD iutessa

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        rsync -avz --delete ./ root@${{ secrets.VPS_HOST }}:/var/www/iutessa/
        ssh root@${{ secrets.VPS_HOST }} 'bash /var/www/iutessa/deploy.sh'

        