# Generated by Django 5.2.5 on 2025-08-15 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la filière')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('places_disponibles', models.PositiveIntegerField(default=60, verbose_name='Places disponibles')),
                ('places_occupees', models.PositiveIntegerField(default=0, verbose_name='Places occupées')),
                ('diplome_requis', models.CharField(default="Diplôme de fin d'étude du second cycle", max_length=200, verbose_name='Diplôme requis')),
                ('domaine_requis', models.CharField(choices=[('general', 'Général'), ('scientifique', 'Scientifique'), ('technique', 'Technique Industrielle'), ('tous', 'Tous domaines confondus')], default='tous', max_length=20, verbose_name='Domaine requis')),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=15000, max_digits=10, verbose_name="Frais d'inscription (FCFA)")),
                ('duree_formation', models.CharField(default='3 ans', max_length=50, verbose_name='Durée de formation')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspendue', 'Suspendue')], default='active', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EtudiantAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=100, verbose_name='Prénoms')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(choices=[('camerounaise', 'Camerounaise'), ('autre', 'Autre')], default='camerounaise', max_length=20, verbose_name='Nationalité')),
                ('region_origine', models.CharField(max_length=50, verbose_name="Région d'origine")),
                ('cni', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]+$', 'Format CNI invalide')], verbose_name='Numéro CNI')),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]+$', 'Numéro de téléphone invalide')], verbose_name='Téléphone')),
                ('email_personnel', models.EmailField(max_length=254, verbose_name='Email personnel')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('nom_pere', models.CharField(max_length=100, verbose_name='Nom du père')),
                ('telephone_pere', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]+$', 'Numéro invalide')], verbose_name='Téléphone père')),
                ('nom_mere', models.CharField(max_length=100, verbose_name='Nom de la mère')),
                ('telephone_mere', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-\\(\\)]+$', 'Numéro invalide')], verbose_name='Téléphone mère')),
                ('diplome_obtenu', models.CharField(max_length=100, verbose_name='Diplôme obtenu')),
                ('annee_obtention', models.PositiveIntegerField(verbose_name="Année d'obtention")),
                ('numero_matricule', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro matricule')),
                ('statut_inscription', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut inscription')),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut validation')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_academique', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='academique.filiere')),
            ],
            options={
                'verbose_name': 'Étudiant Académique',
                'verbose_name_plural': 'Étudiants Académiques',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='ImportEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/etudiants/%Y/%m/', verbose_name='Fichier Excel')),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('nombre_total', models.PositiveIntegerField(default=0)),
                ('nombre_succes', models.PositiveIntegerField(default=0)),
                ('nombre_erreurs', models.PositiveIntegerField(default=0)),
                ('rapport_erreurs', models.TextField(blank=True)),
                ('importe_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Étudiant',
                'verbose_name_plural': 'Imports Étudiants',
                'ordering': ['-date_import'],
            },
        ),
        migrations.CreateModel(
            name='DocumentEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('acte_naissance', 'Acte de naissance'), ('diplome', 'Diplôme du Baccalauréat'), ('releve_notes', 'Relevé de notes'), ('certificat_medical', 'Certificat médical'), ('photo', 'Photo 4x4'), ('recu_paiement', 'Reçu de paiement'), ('lettre_motivation', 'Lettre de motivation')], max_length=20, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to='documents/etudiants/%Y/%m/', verbose_name='Fichier')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='academique.etudiantacademique')),
            ],
            options={
                'verbose_name': 'Document Étudiant',
                'verbose_name_plural': 'Documents Étudiants',
                'ordering': ['-date_upload'],
                'unique_together': {('etudiant', 'type_document')},
            },
        ),
    ]
